apiVersion: v1
kind: ServiceAccount
metadata:
  name: ork-authorizer-service
---
apiVersion: v1
kind: Secret
metadata:
  name: ork-authorizer-secret
  annotations:
    kubernetes.io/service-account.name: ork-authorizer-service
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-ork-authorizer
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterrolebindings", "rolebindings"]
  verbs: ["create", "delete", "get", "list"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "clusterroles"]
  verbs: ["bind"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-ork-authorizer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-ork-authorizer
subjects:
- kind: ServiceAccount
  name: ork-authorizer-service
  namespace: default
