#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn lint  &
yarn cspell --no-progress  &
yarn build  &
yarn markdownlint &

# Commands defined below this line run only if the concurrent commands defined above run successfully
for job in $(jobs -p); do wait "$job" || exit 1; done

yarn test
