# Build & publish docker images
name: Build ork application image pre PR
on:
  pull_request:
    branches-ignore: [ main ]
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:
jobs:
  build:
    name: Build and push ork app image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ork-authorizer-app
        tags: latest ${{ github.sha }}
        context: ./application
        containerfiles: |
          ./application/Dockerfile
