# Build & publish docker images
name: Build ork application image
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:
jobs:
  build:
    name: Build and push ork app image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ork-authorizer-app
        tags: latest ${{ github.sha }}
        context: ./application
        containerfiles: |
          ./application/Dockerfile

    - name: Push To ghcr
      id: push-to-ghcr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ghcr.io/xund-solutions-gmbh
        username: ${{ secrets.GHCR_USER }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-ghcr.outputs.registry-paths }}"
